language: python
python:
- '3.6'
install:
- pip install .
- pip install -r test_requirements.txt
script: pytest
deploy:
  provider: pypi
  user: dchiquit
  password:
    secure: eLKkSytBfZOWm8bSqZP6fuQRd5Go2ZuuSJjx3jZ2jYnlpowBW9LUIye8zWVPhlgQC+QigC+UiOlzmEz1E8LJn64B6xo/s4B23AWEuLm1k1zpMoHJn74l0571iTYO3EZxNIf5PH94lsiDLX7ao3N0Z0zCBl/vCXjcjMoVZBCdeTTjAzXAeya6T8Ztglax89QP2k9O9rkTzJl7Fd2tw08RfUZB+WZUzkCE2B9/YZ6FkbHgpRpUv/7JZk5Tbk2fjpl0+JRM8643cTo24OzGQNYi68wrPkoMdJs9mDBV303jeU7fuip6HmRnEhVjEsSgDlLep2JlNc969Gbiw96PjdCAm/rIo8zsmzVnZvOct6HUivhJ6WZBqupeTV9alyxUHeD1bsABmQaz1TOGCsea64chVP3qF2p6EcogT5rYIZeZNhXPno3gVlcE+aaVOf5CY7CMuoGFSbVEJEpN2kxo+wo9+h5ow1e3D7bMFDCQ2KyvVop/aXquA8qB/2UkcFavobLg4tMa0luyxAJgAkzW/VILoFVx3aMThuMX8lozf0/nksj1Cm6AegmjPWylNI3n30ocYz1rtMZwUMxZYU+ccmrKx7slAnvotqWU8nsw2cYuLn4ZsvFybP5e+wDe6lnHhpXKseb9EU+9Qbscj+xd/PQ3cyGMWREvB0e/ELnylS2B6K8=
  on:
    branch: master
    tags: true
  skip_cleanup: true
