language: python
python:
- '3.6'
install:
- pip install .
- pip install -r test_requirements.txt
script: pytest
deploy:
  provider: pypi
  user: dchiquit
  password:
    secure: ruH8IP4oznyzKEbJbWx+FFiMMtP4iPr9lwU8u8aKUTad6+s8o3pHf9agvPOUZmzUjTV0KA9SyIIbMZSyYtVlDUmlhqdMGKSSc4lQtyCf3mlzaSDFb/g6TMTVACQtfQPREXWtDHixDOeN2F6zRtQYJQ6YfhLAS4AidW7bB98Eu+uFnxk8vPt5LyZ2LFcQubr/Xb26e3ytNP3Ee0S6Y6Fyj92QR80qVwpVowLusyvs6SvWjSbevPZEhvp5MZS1+jjc0hASEVQqy5h+LFmp+46nRQvD7wnpytJBQcliCB+JbA9fNEppFQEYKtSn9wtuAQclI2GwO2PqOcx5xWOXURZFXSjlKgz3HuEQW5HTNVe474ErFKEu8FpD+hgx2ORwHJoGXed36k1GqZxO8TjMzRquVdOvPbzI5xbIu/cIFSJIS1SAlgTaxHrpCaCuqlQWDgxz26pkLJ7LumHXZoRhYPyptz9hM6AwbiXogWwPK1OvSnWiNwYZ7374tjSvjLC92WGQqiZARwoIWvz6jy4yUskyUEtS/16uowDBSJBJaqHa5JC61u9EzZGRIXq25QcC5Uf+DEBUsMzDNjYLgQREAJnUx7wLWNnAQLaATfkzJoyiFGV8vJk9Oj39zU6R+fiP1tkyTOMYLzYrJggS3VVss01nSj6Tocl7/lj5yOyqTKLnuOM=
  on:
    branch: master
    tags: true
  skip_cleanup: true
