language: python
python:
- '3.6'
install:
- pip install .
- pip install -r test_requirements.txt
script: pytest
deploy:
  provider: pypi
  user: dchiquit
  password:
    secure: YbTd8yWk/FQtQwcujiz/AgHY+RBwsoIo4BBESmDyAMjCee1MVsjejB7Q8Z34MGzez90+nwLjyqzoXuuADoDth8BY+8HOG+MCKsKi5+7KQr6Wv9p0997rbw6qky6ims5HNU0Y03/tbBVw9vsya/nxLCQ2+OPco6N7+dYgHwEghLHHG3Mr5uC5mqseqp0Jsx/tEEtbfL+BYGHM3LTOE0ilVlHL8ZU2ql37sYsPA4B3ecNv9g+j4xRjXK6zlGRgVJfP+1Pon0KQPN22qnP6Ku03/9WZZMBx4gQr+Mqus6Al1pSYp9Zxot6JpyLfnvWLLpTAxIfLAvHLvF7W9hUgMHYX6wH8vvGmAgX6PAMvwvmtpubEjN99BnR30B4co+Ypy7HfjxKNSVGuJVUGFNuNpW7ApB3kDfu4b77MiNqKCvAAxa/7AzFVR/F+ICVyu46tBVVExgjnsq14edse9ptwMIiEJTOYobHVRDxh5dFsYcq7BF+3l0qOLW5AHbFQzg+LkGN0/huh9Vl85L/ZZ6oWhCB36zetxrT/2PhGFoIhDDyiXVU2Z8OTKhVa4BoL2p2+pCBwNAsA23WAkM9r9cPJYQNAXyzihIo79+bpMf2o39gw/MdTFcrihnwNqqLOP1Hv9/9Wq6//qJHEZr2Ht/ksl8LZ4lr4zxwgWtg/dfyFuJnhHSk=
  on:
    branch: master
    tags: true
  skip_cleanup: true
